# Generated by Django 2.2.5 on 2019-10-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='feature',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(max_length=5, null=True),
        ),
    ]
