# Generated by Django 2.2.5 on 2019-10-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20191011_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Age',
            new_name='age',
        ),
    ]
