# Generated by Django 2.2.5 on 2019-10-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
