# Generated by Django 2.2.5 on 2019-10-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20191013_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
