# Generated by Django 2.2.5 on 2019-10-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_sub_category'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist_items',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
    ]
