# Generated by Django 2.2.5 on 2019-10-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_sub_category'),
        ('user', '0002_user_wishlist_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart_items',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wishlist_items',
            field=models.ManyToManyField(blank=True, related_name='wishlist_items', to='product.Product'),
        ),
    ]
