# Generated by Django 2.2.5 on 2019-10-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_sub_category'),
        ('user', '0003_auto_20191015_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ordered_items',
            field=models.ManyToManyField(blank=True, related_name='ordered_items', to='product.Product'),
        ),
    ]
